# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20171227_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.ImageField(default='none', upload_to='images/icon'),
            preserve_default=False,
        ),
    ]
