# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, max_length=10)),
                ('senderId', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
