# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-26 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('title', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('publishTime', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(max_length=32)),
            ],
        ),
    ]
