# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-26 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uid',
        ),
    ]
