# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-26 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_post_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
