# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='commentNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='pageview',
            field=models.IntegerField(default=0),
        ),
    ]
