# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20171227_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pageview',
        ),
    ]
